### ISSUE TITLE
Firefox Electrolysis (E10S) Support

### ISSUE THREAD

**Issue by q2r5** [atesh/XKit#193]
Currently on Firefox 38.0a1 with E10S enabled XKit 7.4.5 fails to init with the error `xkit_init(): Permission denied to access property 'errors'`.

The MDN page for porting Add-ons is [here](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox), and the general page on Electrolysis is [here](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox).

**Comment by WyohKnott** [comment]
Yeah, the whole bridge is using XUL stuff and should be rewritten using the addons Sdk…
