### ISSUE TITLE
https doesn't work with xkitcs

### ISSUE THREAD

**Issue by OmgImAlexis** [atesh/XKit#197]
While running the Chrome extension "https everywhere" I can't get xkit to work unless I load https://xkitcs.com and accept the certificate and then reload Tumblr. This happens every time I close and reopen Chrome. Is there any chance you could use a non-self-signed certificate? Maybe look into using Cloudflare's free SSL if need be.

**Comment by hopecraft** [comment]
In a related note, api calls don't detect whether on the page is using encryption or not. Tumblr's servers don't allow Xkit's http calls when using https and vice-versa. Since I use Tumblr via https, I had to manually set https:// for many urls within xkit's internals.

**Comment by unRealElite** [comment]
I've reproduced the same behavior in Firefox 35.0.1. Xkit 7.4.5's API calls didn't return anything from Tumblr's servers until I disabled SSL Everywhere. Now I've got Xkit functioning normally again, good debugging.

**Comment by OmgImAlexis** [comment]
@atesh would it be possible for now to just put xkitcs.com behind Cloudflare's Flexible SSL? At least then you'd have a signed certificate.
