### ISSUE TITLE
Potential Extension Conflicts

### ISSUE THREAD

**Issue by bjornstar** [atesh/XKit#203]
![potential-extension-conflicts](https://cloud.githubusercontent.com/assets/20630/7059397/81a04bcc-deab-11e4-98d3-54262249869b.png)

Several users are reporting this warning.

http://supertrainstationh.tumblr.com/post/115889279797/is-this-from-using-both-tumblr-savior-and-xkit-in
http://p-joblog.tumblr.com/post/115877355026/uhm-anybody-else-got-this-upon-opening-tumblr

This warning message is really hostile towards other extensions. Please don't throw us under the bus when your extension explodes on a tumblr update. There's plenty of room for all of us in the browser.

**Comment by Zarggg** [comment]
I received this message earlier, as well. No extensions were listed and I haven't seen anything new break.

**Comment by bjornstar** [comment]
The problem is that tumblr changed their code and this warning is blaming it on some "unknown extension"

The code is here https://github.com/atesh/XKit/blob/66481a662dfe94c8af9f50c6fcc21990f7e367ed/xkit.js#L786

Tumblr removed the likes and following section in the sidebar.

Removing other extensions will not make this warning go away, your only options are to ignore and continue or disable xkit.

It would be much more friendly if xkit simply said it detected a problem and it might be because tumblr updated or another extension is interfering. Recommending disabling or removing other extensions is hostile. You can suggest people review their installed extensions for possible conflicts instead.

The big scary language threatening people that they won't be supported is wholly unnecessary.

**Comment by Theliahh** [comment]
As far as I know, this is referring to Xkit extensions, not Chrome/Firefox extensions.

**Comment by Zarggg** [comment]
@bjornstar: That makes sense.

@Theliahh: I saw a few posts *about* him being harassed, but nothing firsthand. If so, that's terrible I'm I hope that kind of abuse stops.

**Comment by aureljared** [comment]
@Zarggg Yeah, a lot of people were sending him hate because IIRC they said he was racist and stuff - even though he was part of the race in question.

Back on topic though, resetting XKit gives an `error 100`, which seems to be a certificate issue - might be just my system though, reinstalling gives no problems.
Tested on Chrome 41, broken on FF 37.

**Comment by ricardoedm** [comment]
I can't imagine what people had to do before the days of internet searching.  I got this message a few times, tried disabling all my extensions and nothing worked, and THEN I thought of doing a search and found this thread.  Anyway, thanks for the info guys, good to know that the pesky pop up is irritating but there is nothing I can do.  As for Atesh being harassed, that's a real shame.  The product may not have been perfect but really, people can be total A-holes, specially when something is free or when <gasp> they pay less than the price of a cup of coffee to use a product

**Comment by peterjeliot** [comment]
+1 for this being cause by something other than my browser extensions. Even disabling them all, I still get this.

**Comment by swyrl** [comment]
aww poor Atesh :(
but yeah, good to know.

**Comment by bjornstar** [comment]
Considering this project is dead, no reason to keep this open.
