### ISSUE TITLE
Fail to install due to SSL error

### ISSUE THREAD

**Issue by cdl** [atesh/XKit#216]
Looks like XKit is now failing to install due to a `NET::ERR_CERT_DATE_INVALID` error from Chrome when trying to fetch resources from `https://www.xkitcs.com/seven`.

Running Chrome `v48.0.2564.116`, XKit `v7.5.1`.

**Comment by SpeedyD** [comment]
XKit is no longer supported, go for New XKit instead:
https://new-xkit-extension.tumblr.com/

2016-02-27 1:42 GMT+01:00 Colby Ludwig <notifications@github.com>:

**Comment by cdl** [comment]
@SpeedyD ah, thanks!
